RaspPi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('',include('accounts.urls',)),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('product-specs/', include('specs.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('add_qty/<int:product_id>/', views.add_quantity,name='change_qty'),
    path('subtraction_quantity/<int:product_id>/',views.subtraction_quantity,name='subtraction_quantity')
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

cart/models.py
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils import timezone

from accounts.models import User
from mainapp.models import Product


class CartProduct(models.Model):
    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    product = models.ForeignKey(Product, verbose_name='Товар', on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return "Продукт: {} (для корзины)".format(self.product.title)

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.product.price
        super().save(*args, **kwargs)


class Cart(models.Model):
    owner = models.ForeignKey('Customer', verbose_name='Власник', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):
    user = models.ForeignKey(User, verbose_name='Пользователь',on_delete=models.SET_NULL, null=True, blank=True)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)
    orders = models.ManyToManyField('Order', verbose_name='Заказы покупателя', related_name='related_order')

    def __str__(self):
        return "Покупатель: {} {}".format(self.user.first_name, self.user.last_name)


class Order(models.Model):
    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Нове замовлення'),
        (STATUS_IN_PROGRESS, 'Замовлення в обробці'),
        (STATUS_READY, 'Замовлення готове'),
        (STATUS_COMPLETED, 'Замовлення виконано')
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Доставка')
    )

    customer = models.ForeignKey(Customer, verbose_name='Покупатель', related_name='related_orders',
                                 on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=1024, verbose_name='Адрес', null=True, blank=True)
    status = models.CharField(
        max_length=100,
        verbose_name='Статус заказ',
        choices=STATUS_CHOICES,
        default=STATUS_NEW
    )
    buying_type = models.CharField(
        max_length=100,
        verbose_name='Тип заказа',
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_SELF
    )
    comment = models.TextField(verbose_name='Комментарий к заказу', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')
    order_date = models.DateField(verbose_name='Дата получения заказа', default=timezone.now)

    def __str__(self):
        return str(self.id)

cart/forms.py
# from django import forms
#
# PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
#
# class CartAddProductForm(forms.Form):
#     quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, required=False ,coerce=int)
#     update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
import http
import json

from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from mainapp.models import Product, Category
from order.models import OrderItem, Order
from .cart import Cart


def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product=product)
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def add_quantity(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add_quantity(product)
    return redirect(request.META['HTTP_REFERER'])

def subtraction_quantity(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.subtraction_quantity(product)
    return redirect(request.META['HTTP_REFERER'])


def cart_detail(request):
    cart = Cart(request)
    categories = Category.objects.all()
    return render(request, 'cart/cart.html', {'cart': cart, 'categories': categories})

cart/templates/cart/cart.html
{% extends "mainapp/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Your shopping cart
{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'cart/css/main.css' %}">
    <scripts src="{% static 'cart/js/cart.js' %}"></scripts>
{% endblock %}
{% block content %}
	<div class="container row" style="margin: 0 auto">
		<div class="col-lg-12">
			<div class="box-element">
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{cart.get_total_item}}</strong></h5></th>
						<th><h5>Total:<strong>{{cart.get_total_price}} грн</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'order:order_create' %}">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				{% for item in cart %}
                    {% with product=item.product %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.img.url}}"></div>
					<div style="flex:2"><p>{{item.product.title}}</p></div>
					<div style="flex:1"><p>${{item.price|floatformat:2}}</p></div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity" id="quantity">
                            <a href="{% url 'cart:change_qty' product.id %} ">
                                <img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'cart/images/arrow-up.png' %}">
                            </a>
                            <a href="{% url 'cart:subtraction_quantity' product.id %}">
                                <img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'cart/images/arrow-down.png' %}">
                            </a>
						</div>
					</div>
					<div style="flex:1"><p>${{item.total_price|floatformat:2}}</p></div>
                <a href="{% url "cart:cart_remove" product.id %}"
                                        class=" btn-sm">X</a></td>
				</div>
                    {% endwith %}
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock content %}

cart/templates/cart/checkout.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block css %} <link rel="stylesheet" href="{% static 'cart/css/main.css' %}"> {% endblock %}
{% block content %}
     <div class="row" style="max-width:1300px; margin: 0 auto">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>

					<div id="shipping-info">
						<hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Zip code..">
						</div>
					</div>

					<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
				</form>
			</div>
		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<hr>
				<h3>Ваша корзина</h3>
				<hr>
				{% for item in cart %}
                    {% with product=item.product %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.img.url}}"></div>
					<div style="flex:2"><p>{{item.product.title}}</p></div>
					<div style="flex:1"><p>${{item.price|floatformat:2}}</p></div>
					<div style="flex:1"><p>x{{item.quantity}}</p></div>
				</div>
				{% endwith %}
				{% endfor %}
                <h5>Разом::<strong> {{cart.get_total_price}} грн</strong></h5>
			</div>
		</div>
	</div>
{% endblock content %}

cart/templates/cart/detail.html
{% extends "mainapp/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Your shopping cart
{% endblock %}
{% block content %}


<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0"><a href="index.html">Home</a> <span class="mx-2 mb-0">/</span> <strong
                    class="text-black">Cart</strong></div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <form class="col-md-12" method="post">
                <div class="site-blocks-table">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th class="product-thumbnail">Image</th>
                                <th class="product-name">Product</th>
                                <th class="product-price">Price</th>
                                <th class="product-quantity">Quantity</th>
                                <th class="product-total">Total</th>
                                <th class="product-remove">Remove</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>{% for item in cart %}
                                {% with product=item.product %}
                            <tr>
                                <td class="product-thumbnail">
                                    <img src="{{ item.product.img.url }}" alt="Image" class="img-fluid">
                                </td>
                                <td class="product-name">
                                    <h2 class="h5 text-black">{{ item.product.title }}</h2>
                                </td>
                                <td>${{ item.price }}</td>
                                <td>
                                    <div class="input-group mb-3" style="max-width: 120px;">
                                        <div class="input-group-prepend">
                                            <form action="{% url "cart:cart_add" product.id %}" method="get">

                                                {{ item.update_quantity_form.quantity }}
                                                {{ item.update_quantity_form.override }}
                                                <input class="btn btn-outline-primary js-btn-plus" type="submit"
                                                    value="Update">
                                            </form>
                                        </div>
                                    </div>
                                </td>
                                <td>${{ item.total_price }}</td>
                                <td><a href="{% url "cart:cart_remove" product.id %}"
                                        class="btn btn-primary btn-sm">X</a></td>
                            </tr>
                            {% endwith %}
                            {% endfor %}
                            </tr>

                        </tbody>
                    </table>
                </div>
            </form>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="row mb-5">
<!--                    <div class="col-md-6 mb-3 mb-md-0">-->
<!--                        <button onclick="window.location=''" class="btn btn-primary btn-sm btn-block">Continue Shopping</button>-->
<!--                    </div>-->
                    <div class="col-md-6">
                        <button class="btn btn-outline-primary btn-sm btn-block">Checkout</button>
                    </div>
                </div>
<!--                <div class="row">-->
<!--                    <div class="col-md-12">-->
<!--                        <label class="text-black h4" for="coupon">Coupon</label>-->
<!--                        <p>Enter your coupon code if you have one.</p>-->
<!--                    </div>-->
<!--                    <form action="" method="post">-->
<!--                        {% csrf_token %}-->
<!--                        <div class="col-md-8 mb-3 mb-md-0">-->
<!--                            -->
<!--                        </div>-->
<!--                        <div class="col-md-4">-->
<!--                            <button type="submit" class="btn btn-primary btn-sm">Apply Coupon</button>-->
<!--                        </div>-->
<!--                    </form>-->
<!--                </div>-->
            </div>
            <div class="col-md-6 pl-5">
                <div class="row justify-content-end">
                    <div class="col-md-7">
                        <div class="row">
                            <div class="col-md-12 text-right border-bottom mb-5">
                                <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                            </div>
                        </div>

                        <div class="row mb-5">
                            <div class="col-md-6">
                                <span class="text-black">Total</span>
                            </div>
                            <div class="col-md-6 text-right">
                                <strong class="text-black">{{ cart.get_total_price_after_discount|floatformat:"2" }}</strong>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <button class="btn btn-primary btn-lg py-3 btn-block"
                                    onclick="window.location='{% url "order:order_create" %}'">Proceed To Checkout</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}